In [32]:
import seaborn as sns
df=sns.load_dataset('Titanic')
import warnings
warnings.filterwarnings('ignore')

In [33]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [34]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [35]:
from sklearn.impute import SimpleImputer

def age_(data):
    imp=SimpleImputer(strategy= 'mean')
    data['age']=imp.fit_transform(data[['age']])
    return data

df=age_(df)

In [36]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [37]:
cat_imp=SimpleImputer(strategy='most_frequent')

df['embark_town']=cat_imp.fit_transform(df[['embark_town']]).ravel()

In [40]:


def preprocess(data):
    data['class']=data['class'].map({
        'Third':1,
        'Second':2,
        'First':3
    })
    data['who']=data['who'].map({
        'child':3,
        'woman':2,
        'man':1
    })
    data['adult_male']=data['adult_male'].map({
        True:1,
        False:0
    })
    return data

df=preprocess(df)

In [41]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,1,1,1,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,3,2,0,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,1,2,0,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,3,2,0,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,1,1,1,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,2,1,1,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,3,2,0,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,1,2,0,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,3,1,1,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,1,1,1,NaN,Queenstown,no,True

In [43]:
x=df.drop(['survived','deck','embark_town','alive','embarked','sex'],axis=1)
y=df['survived']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=42)

In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [45]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       157
           1       0.81      0.73      0.77       111

    accuracy                           0.82       268
   macro avg       0.82      0.80      0.81       268
weighted avg       0.82      0.82      0.82       268